*** empty log message ***

diff --git a/example/test b/example/test
--- a/example/test
+++ b/example/test
@@ -4,57 +4,101 @@
 #
 # Distributed under the Boost Software License, Version 1.0.
 
-TIMEFORMAT='Time: %R seconds'
+TIMEFORMAT='  Time: %R seconds'
 
 f=$1
 
-echo "Testing '$f'..."
+if ! echo "$f" | grep -e '\.cpp$' -e '\.c$' > /dev/null ; then
+    echo "Error '$f' is neither a C nor C++ implementation file."
+    exit 1
+fi
 
-time cpp -I ../inc/ -I ../../chaos-pp/ "$f" > ".tmp"
+function is-cpp {
+    echo "$1" | grep '\.\(cpp\|ii\)$' > /dev/null
+}
 
-numPrefixLines=$(grep -n -e 'order/interpreter.h' ".tmp" | tail -n1 | grep -o '^[0-9]\+')
-numLines=$(cat ".tmp" | wc -l)
-cat ".tmp" | tail -n$(($numLines - $numPrefixLines)) | grep -v -e '^#' -e '^$' > ".$f.new"
-rm ".tmp"
+function preprocessed-file {
+    echo ".$1" | sed -e 's#\.cpp$#.ii#g' -e 's#\.c$#.i#g'
+}
+
+function compile {
+    if is-cpp "$1" ; then
+        time g++ -c -std=c++98 -Wall -Werror -pedantic-errors "$1"
+    else
+        time gcc -c -std=c99 -Wall -Werror -pedantic-errors "$1"
+    fi && \
+    rm "$(echo "$1" | sed 's#\.[^.]\+$#.o#g')"
+}
+
+function preprocess {
+    if is-cpp "$1" ; then
+        # TBD: We can't used -pedantic here due to variadic macros.
+        time g++ -E -std=c++98 -Wall -I ../inc/ -I ../../chaos-pp/ "$1"
+    else
+        time gcc -E -std=c99 -Wall -Werror -pedantic-errors -I ../inc/ -I ../../chaos-pp/ "$1"
+    fi
+}
+
+echo "Testing '$f':"
+
+echo " Preprocessing..."
+if ! preprocess "$f" > "$(preprocessed-file "$f")" ; then
+    echo "Error preprocessing '$f'."
+    exit 1
+fi
+
+if grep '^[ \t]*[^#]' "$(preprocessed-file "$f")" > /dev/null ; then
+    echo " Compiling..."
+    if ! compile "$(preprocessed-file "$f")" ; then
+        echo "Error compiling '$f'."
+        exit 1
+    fi
+else
+    echo " Empty output. Skipping compilation."
+fi
+
+numPrefixLines=$(grep -n -e 'order/interpreter.h' "$(preprocessed-file "$f")" | tail -n1 | grep -o '^[0-9]\+')
+numLines=$(cat "$(preprocessed-file "$f")" | wc -l)
+cat "$(preprocessed-file "$f")" | tail -n$(($numLines - $numPrefixLines)) | grep -v -e '^#' -e '^$' > ".$f.new"
 
 if test -f ".$f.out" ; then
     if diff -q ".$f.out" ".$f.new" > /dev/null ; then
         rm ".$f.new"
     else
-        echo "The old and new output differ!"
+        echo " The old and new output differ!"
         diff ".$f.out" ".$f.new" | less
 
-        read -e -n 1 -p "[(U)se new result | (E)xit without removing new output | (Q)uit | Skip]? "
+        read -e -n 1 -p " [(Q)uit | (U)se new result | (S)kip without removing new output | Skip]? "
         case "$REPLY" in
             ("u"|"U")
-            echo "Using new result..."
+            echo " Using new result..."
             mv ".$f.new" ".$f.out" ;;
-            ("e"|"E")
-            echo "Quitting... See the file '.$f.new'."
+            ("s"|"S")
+            echo " Skipping... See the file '.$f.new'."
             exit ;;
             ("q"|"Q")
-            echo "Quitting and removing '.$f.new'..."
+            echo " Quitting and removing '.$f.new'..."
             rm ".$f.new"
-            exit ;;
+            exit 1 ;;
             (*)
-            echo "Skipping and removing '.$f.new'..."
+            echo " Skipping and removing '.$f.new'..."
             rm ".$f.new" ;;
         esac
     fi
 else
     less ".$f.new"
 
-    read -e -n 1 -p "[(E)xit without removing output | (Q)uit | Use result]? "
+    read -e -n 1 -p " [(Q)uit | (S)kip without removing output | Use result]? "
     case "$REPLY" in
-        ("e"|"E")
-        echo "Quitting... See the file '.$f.new'."
-        exit ;;
         ("q"|"Q")
-        echo "Quitting and removing '.$f.new'..."
+        echo " Quitting and removing '.$f.new'..."
         rm ".$f.new"
+        exit 1 ;;
+        ("s"|"S")
+        echo " Skipping... See the file '.$f.new'."
         exit ;;
         (*)
-        echo "Using result..."
+        echo " Using result..."
         mv ".$f.new" ".$f.out" ;;
     esac
 fi
